#!/usr/bin/env python

import rospy
from std_msgs.msg import String
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)


L1=18
L2 =17
R1=23
R2=22
GPIO.setup(L1,GPIO.OUT)
GPIO.setup(L2,GPIO.OUT)
GPIO.setup(R1,GPIO.OUT)
GPIO.setup(R2,GPIO.OUT)

def StopMotors():
    GPIO.output(L1,0)
    GPIO.output(L2,0)
    GPIO.output(R1,0)
    GPIO.output(R2,0)	
def Forwards():
    GPIO.output(L1,1)
    GPIO.output(L2,0)
    GPIO.output(R1,1)
    GPIO.output(R2,0)	
def Backwards():
    GPIO.output(L1,0)
    GPIO.output(L2,1)
    GPIO.output(R1,0)
    GPIO.output(R2,1)
def Left():
    GPIO.output(L1,0)
    GPIO.output(L2,1)
    GPIO.output(R1,1)
    GPIO.output(R2,0)
def Right():
    GPIO.output(L1,1)
    GPIO.output(L2,0)
    GPIO.output(R1,0)
    GPIO.output(R2,1)
	
def CommandCallback(commandMessage):
    command = commandMessage.data
    if command == 'forwards':
        print('Moving forwards')
        Forwards()
    elif command == 'backwards':
        print('Moving backwards')
        Backwards()
    elif command == 'left':
        print('Turning left')
        Left()
    elif command == 'right':
        print('Turning right')
        Right()
    elif command == 'stop':
        print('Stopping')
        StopMotors()
    else:
        print('Unknown command, stopping instead')
        StopMotors()

rospy.init_node('driver')

rospy.Subscriber('command', String, CommandCallback)

rospy.spin()
print('Shutting down: stopping motors')
StopMotors()
GPIO.cleanup()	
	
